[project]
name = "neuraldigest_llm"
authors = [
    {name = "Liam Pieri", email = "pieri.liam@gmail.com"}
    ]
description = "LLM NeuralDigest"

[flake8]
max-line-length = 88
extend-ignore = "E203"

[tool.isort]
profile = "black"
